spring:
  application:
    name: DevSync

  datasource:
    url: jdbc:postgresql://localhost:5432/devsync_db
    username: postgres
    password: 8520
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
        order_updates: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB
app:
  jwt:
    secret: ReplaceThisWithVeryLongSecure256BitSecretKeyValue
    expiration-ms: 90000000
  storage:
    upload-dir: uploads
